package ru.V5Minecraft.MultiColoredBlocks.Register;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import ru.V5Minecraft.MultiColoredBlocks.blocks.*;

public class RegisterBlocks {
    public static Block RedPlanks = new Wood("red_planks", "redplanks");
    public static Block OrangePlanks = new Wood("orange_planks", "orangeplanks");
    public static Block YellowPlanks = new Wood("yellow_planks", "yellowplanks");
    public static Block GreenPlanks = new Wood("green_planks", "greenplanks");
    public static Block LightBluePlanks = new Wood("lightblue_planks", "lightblueplanks");
    public static Block BluePlanks = new Wood("blue_planks", "blueplanks");
    public static Block PurplePlanks = new Wood("purple_planks", "purpleplanks");
    public static Block BlackWhitePlanks = new Wood("black_white_planks", "blackwhiteplanks");
    public static Block RedStair = new Stair("red_stair", "redplanks", RedPlanks, 0);
    public static Block OrangeStair = new Stair("orange_stair", "orangeplanks", OrangePlanks, 0);
    public static Block YellowStair = new Stair("yellow_stair", "yellowplanks", YellowPlanks, 0);
    public static Block GreenStair = new Stair("green_stair", "greenplanks", GreenPlanks, 0);
    public static Block LightBlueStair = new Stair("lightblue_stair", "lightblueplanks", LightBluePlanks, 0);
    public static Block BlueStair = new Stair("blue_stair", "blueplanks", BluePlanks, 0);
    public static Block PurpleStair = new Stair("purple_stair", "purpleplanks", PurplePlanks, 0);
    public static Block BlackWhiteStair = new Stair("black_white_stair", "blackwhiteplanks", BlackWhitePlanks, 0);
    public static Block RedDoorBlock = new Door("red");
    public static Block OrangeDoorBlock = new Door("orange");
    public static Block YellowDoorBlock = new Door("yellow");
    public static Block GreenDoorBlock = new Door("green");
    public static Block LightBlueDoorBlock = new Door("lightblue");
    public static Block BlueDoorBlock = new Door("blue");
    public static Block PurpleDoorBlock = new Door("purple");
    public static Block BlackWhiteDoorBlock = new Door("blackwhite");
    public static Block RedCraftingTable = new RedCraftingTable("red_crafting_table");
    public static Block OrangeCraftingTable = new OrangeCraftingTable("orange_crafting_table");
    public static Block YellowCraftingTable = new YellowCraftingTable("yellow_crafting_table");
    public static Block GreenCraftingTable = new GreenCraftingTable("green_crafting_table");
    public static Block LightBlueCraftingTable = new LightBlueCraftingTable("lightblue_crafting_table");
    public static Block BlueCraftingTable = new BlueCraftingTable("blue_crafting_table");
    public static Block PurpleCraftingTable = new PurpleCraftingTable("purple_crafting_table");
    public static Block BlackWhiteCraftingTable = new BlackWhiteCraftingTable("black_white_crafting_table");
    public static Block RedIronBars = new IronBars("red_iron_bars", "red_iron_bars", "red_iron_bars", "red");
    public static Block OrangeIronBars = new IronBars("orange_iron_bars", "orange_iron_bars", "orange_iron_bars", "orange");
    public static Block YellowIronBars = new IronBars("yellow_iron_bars", "yellow_iron_bars", "yellow_iron_bars", "yellow");
    public static Block GreenIronBars = new IronBars("green_iron_bars", "green_iron_bars", "green_iron_bars", "green");
    public static Block LightBlueIronBars = new IronBars("lightblue_iron_bars", "lightblue_iron_bars", "lightblue_iron_bars", "lightblue");
    public static Block BlueIronBars = new IronBars("blue_iron_bars", "blue_iron_bars", "blue_iron_bars", "blue");
    public static Block PurpleIronBars = new IronBars("purple_iron_bars", "purple_iron_bars", "purple_iron_bars", "purple");
    public static Block BlackWhiteIronBars = new IronBars("black_white_iron_bars", "black_white_iron_bars", "black_white_iron_bars", "blackwhite");
    public static Block RedOakLog = new OakLog("red_oak_log", "red");
    public static Block OrangeOakLog = new OakLog("orange_oak_log", "orange");
    public static Block YellowOakLog = new OakLog("yellow_oak_log", "yellow");
    public static Block GreenOakLog = new OakLog("green_oak_log", "green");
    public static Block LightBlueOakLog = new OakLog("lightblue_oak_log", "lightblue");
    public static Block BlueOakLog = new OakLog("blue_oak_log", "blue");
    public static Block PurpleOakLog = new OakLog("purple_oak_log", "purple");
    public static Block BlackWhiteOakLog = new OakLog("black_white_oak_log", "blackwhite");
    public static Block RedTrapDoor = new TrapDoor("red_trapdoor", "redtrapdoor");
    public static Block OrangeTrapDoor = new TrapDoor("orange_trapdoor", "orangetrapdoor");
    public static Block YellowTrapDoor = new TrapDoor("yellow_trapdoor", "yellowtrapdoor");
    public static Block GreenTrapDoor = new TrapDoor("green_trapdoor", "greentrapdoor");
    public static Block LightBlueTrapDoor = new TrapDoor("lightblue_trapdoor", "lightbluetrapdoor");
    public static Block BlueTrapDoor = new TrapDoor("blue_trapdoor", "bluetrapdoor");
    public static Block PurpleTrapDoor = new TrapDoor("purple_trapdoor", "purpletrapdoor");
    public static Block BlackWhiteTrapDoor = new TrapDoor("black_white_trapdoor", "blackwhitetrapdoor");
    public static Block RedLadder = new Ladder("red_ladder", "redladder");
    public static Block OrangeLadder = new Ladder("orange_ladder", "orangeladder");
    public static Block YellowLadder = new Ladder("yellow_ladder", "yellowladder");
    public static Block GreenLadder = new Ladder("green_ladder", "greenladder");
    public static Block LightBlueLadder = new Ladder("lightblue_ladder", "lightblueladder");
    public static Block BlueLadder = new Ladder("blue_ladder", "blueladder");
    public static Block PurpleLadder = new Ladder("purple_ladder", "purpleladder");
    public static Block BlackWhiteLadder = new Ladder("black_white_ladder", "blackwhiteladder");
    public static Block RedWoodenFence = new Fence("red_wooden_fence", "red");
    public static Block OrangeWoodenFence = new Fence("orange_wooden_fence", "orange");
    public static Block YellowWoodenFence = new Fence("yellow_wooden_fence", "yellow");
    public static Block GreenWoodenFence = new Fence("green_wooden_fence", "green");
    public static Block LightBlueWoodenFence = new Fence("lightblue_wooden_fence", "lightblue");
    public static Block BlueWoodenFence = new Fence("blue_wooden_fence", "blue");
    public static Block PurpleWoodenFence = new Fence("purple_wooden_fence", "purple");
    public static Block BlackWhiteWoodenFence = new Fence("black_white_wooden_fence", "blackwhite");
    public static Block RedWoodenFenceGate = new RedFenceGate("red_wooden_fence_gate");
    public static Block OrangeWoodenFenceGate = new OrangeFenceGate("orange_wooden_fence_gate");
    public static Block YellowWoodenFenceGate = new YellowFenceGate("yellow_wooden_fence_gate");
    public static Block GreenWoodenFenceGate = new GreenFenceGate("green_wooden_fence_gate");
    public static Block LightBlueWoodenFenceGate = new LightBlueFenceGate("lightblue_wooden_fence_gate");
    public static Block BlueWoodenFenceGate = new BlueFenceGate("blue_wooden_fence_gate");
    public static Block PurpleWoodenFenceGate = new PurpleFenceGate("purple_wooden_fence_gate");
    public static Block BlackWhiteWoodenFenceGate = new BlackWhiteFenceGate("black_white_wooden_fence_gate");
    public static Block RedFurnace = new RedFurnace("red_furnace", false);
    public static Block RedFurnaceOn = new RedFurnace("redfurnaceon", true);

    public static void register() {
        GameRegistry.registerBlock(RedPlanks, "red_planks");
        GameRegistry.registerBlock(OrangePlanks, "orange_planks");
        GameRegistry.registerBlock(YellowPlanks, "yellow_planks");
        GameRegistry.registerBlock(GreenPlanks, "green_planks");
        GameRegistry.registerBlock(LightBluePlanks, "lightblue_planks");
        GameRegistry.registerBlock(BluePlanks, "blue_planks");
        GameRegistry.registerBlock(PurplePlanks, "purple_planks");
        GameRegistry.registerBlock(BlackWhitePlanks, "black_white_planks");
        GameRegistry.registerBlock(RedStair, "red_stair");
        GameRegistry.registerBlock(OrangeStair, "orange_stair");
        GameRegistry.registerBlock(YellowStair, "yellow_stair");
        GameRegistry.registerBlock(GreenStair, "green_stair");
        GameRegistry.registerBlock(LightBlueStair, "lightblue_stair");
        GameRegistry.registerBlock(BlueStair, "blue_stair");
        GameRegistry.registerBlock(PurpleStair, "purple_stair");
        GameRegistry.registerBlock(BlackWhiteStair, "black_white_stair");
        GameRegistry.registerBlock(RedDoorBlock, "red_wooden_door_block");
        GameRegistry.registerBlock(OrangeDoorBlock, "orange_wooden_door_block");
        GameRegistry.registerBlock(YellowDoorBlock, "yellow_wooden_door_block");
        GameRegistry.registerBlock(GreenDoorBlock, "green_wooden_door_block");
        GameRegistry.registerBlock(LightBlueDoorBlock, "lightblue_wooden_door_block");
        GameRegistry.registerBlock(BlueDoorBlock, "blue_wooden_door_block");
        GameRegistry.registerBlock(PurpleDoorBlock, "purple_wooden_door_block");
        GameRegistry.registerBlock(BlackWhiteDoorBlock, "black_white_wooden_door_block");
        GameRegistry.registerBlock(RedCraftingTable, "red_crafting_table");
        GameRegistry.registerBlock(OrangeCraftingTable, "orange_crafting_table");
        GameRegistry.registerBlock(YellowCraftingTable, "yellow_crafting_table");
        GameRegistry.registerBlock(GreenCraftingTable, "green_crafting_table");
        GameRegistry.registerBlock(LightBlueCraftingTable, "lightblue_crafting_table");
        GameRegistry.registerBlock(BlueCraftingTable, "blue_crafting_table");
        GameRegistry.registerBlock(PurpleCraftingTable, "purple_crafting_table");
        GameRegistry.registerBlock(BlackWhiteCraftingTable, "black_white_crafting_table");
        GameRegistry.registerBlock(RedIronBars, "red_iron_bars");
        GameRegistry.registerBlock(OrangeIronBars, "orange_iron_bars");
        GameRegistry.registerBlock(YellowIronBars, "yellow_iron_bars");
        GameRegistry.registerBlock(GreenIronBars, "green_iron_bars");
        GameRegistry.registerBlock(LightBlueIronBars, "lightblue_iron_bars");
        GameRegistry.registerBlock(BlueIronBars, "blue_iron_bars");
        GameRegistry.registerBlock(PurpleIronBars, "purple_iron_bars");
        GameRegistry.registerBlock(BlackWhiteIronBars, "black_white_iron_bars");
        GameRegistry.registerBlock(RedOakLog, "red_oak_log");
        GameRegistry.registerBlock(OrangeOakLog, "orange_oak_log");
        GameRegistry.registerBlock(YellowOakLog, "yellow_oak_log");
        GameRegistry.registerBlock(GreenOakLog, "green_oak_log");
        GameRegistry.registerBlock(LightBlueOakLog, "lightblue_oak_log");
        GameRegistry.registerBlock(BlueOakLog, "blue_oak_log");
        GameRegistry.registerBlock(PurpleOakLog, "purple_oak_log");
        GameRegistry.registerBlock(BlackWhiteOakLog, "black_white_oak_log");
        GameRegistry.registerBlock(RedTrapDoor, "red_trapdoor");
        GameRegistry.registerBlock(OrangeTrapDoor, "orange_trapdoor");
        GameRegistry.registerBlock(YellowTrapDoor, "yellow_trapdoor");
        GameRegistry.registerBlock(GreenTrapDoor, "green_trapdoor");
        GameRegistry.registerBlock(LightBlueTrapDoor, "lightblue_trapdoor");
        GameRegistry.registerBlock(BlueTrapDoor, "blue_trapdoor");
        GameRegistry.registerBlock(PurpleTrapDoor, "purple_trapdoor");
        GameRegistry.registerBlock(BlackWhiteTrapDoor, "black_white_trapdoor");
        GameRegistry.registerBlock(RedLadder, "red_ladder");
        GameRegistry.registerBlock(OrangeLadder, "orange_ladder");
        GameRegistry.registerBlock(YellowLadder, "yellow_ladder");
        GameRegistry.registerBlock(GreenLadder, "green_ladder");
        GameRegistry.registerBlock(LightBlueLadder, "lightblue_ladder");
        GameRegistry.registerBlock(BlueLadder, "blue_ladder");
        GameRegistry.registerBlock(PurpleLadder, "purple_ladder");
        GameRegistry.registerBlock(BlackWhiteLadder, "black_white_ladder");
        GameRegistry.registerBlock(RedWoodenFence, "red_wooden_fence");
        GameRegistry.registerBlock(OrangeWoodenFence, "orange_wooden_fence");
        GameRegistry.registerBlock(YellowWoodenFence, "yellow_wooden_fence");
        GameRegistry.registerBlock(GreenWoodenFence, "green_wooden_fence");
        GameRegistry.registerBlock(LightBlueWoodenFence, "lightblue_wooden_fence");
        GameRegistry.registerBlock(BlueWoodenFence, "blue_wooden_fence");
        GameRegistry.registerBlock(PurpleWoodenFence, "purple_wooden_fence");
        GameRegistry.registerBlock(BlackWhiteWoodenFence, "black_white_wooden_fence");
        GameRegistry.registerBlock(RedWoodenFenceGate, "red_wooden_fence_gate");
        GameRegistry.registerBlock(OrangeWoodenFenceGate, "orange_wooden_fence_gate");
        GameRegistry.registerBlock(YellowWoodenFenceGate, "yellow_wooden_fence_gate");
        GameRegistry.registerBlock(GreenWoodenFenceGate, "green_wooden_fence_gate");
        GameRegistry.registerBlock(LightBlueWoodenFenceGate, "lightblue_wooden_fence_gate");
        GameRegistry.registerBlock(BlueWoodenFenceGate, "blue_wooden_fence_gate");
        GameRegistry.registerBlock(PurpleWoodenFenceGate, "purple_wooden_fence_gate");
        GameRegistry.registerBlock(BlackWhiteWoodenFenceGate, "black_white_wooden_fence_gate");
        GameRegistry.registerBlock(RedFurnace, "red_furnace");
        GameRegistry.registerBlock(RedFurnaceOn, "redfurnaceon");
    }
}
